
execute pathogen#infect()
filetype plugin indent on

"colorscheme elflord
colorscheme desert

"set smartindent
set cindent
set cinkeys-=0#
set indentkeys-=0#
set tabstop=4
set shiftwidth=4
set expandtab
set background=dark
set hidden
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:< 

set number
syntax on

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=2       "deepest fold is 2 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use
" Folding color:

" In normal mode, press Space to toggle the current fold open/closed. However,
" if the cursor is not in a fold, move to the right (the default behavior). In
" addition, with the manual fold method, you can create a fold by visually
" selecting some lines, then pressing Space.
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf

let mapleader=","

set backspace=indent,eol,start

"set mouse=a

"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/

"http://stackoverflow.com/questions/2447109/showing-a-different-background-colour-in-vim-past-80-characters
"let &colorcolumn=join(range(81,999),",")
"highlight ColorColumn ctermbg=235 guibg=#2c2d27
"let &colorcolumn="80,".join(range(120,999),",")

"set textwidth=80
set colorcolumn=+1
" light grey
hi ColorColumn guibg=#2d2d2d ctermbg=235

" dark grey 
" hi ColorColumn guibg=#2d2d2d ctermbg=246

set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

map <F7> mzgg=G`z<CR>

let g:VimuxUseNearestPane = 1

" Vimux
map <silent> <LocalLeader>rl :wa<CR> :VimuxRunLastCommand<CR>
map <silent> <LocalLeader>vi :wa<CR> :VimuxInspectRunner<CR>
map <silent> <LocalLeader>vk :wa<CR> :VimuxInterruptRunner<CR>
map <silent> <LocalLeader>vx :wa<CR> :VimuxClosePanes<CR>
map <silent> <LocalLeader>vp :VimuxPromptCommand<CR>
vmap <silent> <LocalLeader>vs "vy :call VimuxRunCommand(@v)<CR>
nmap <silent> <LocalLeader>vs vip<LocalLeader>vs<CR>

let g:tmux_sessionname='0'
let g:tmux_windowname='./ipython.sh'
let g:tmux_panenumber='0'
let g:vimux_pyutils_use_tslime=1

"-- Tabbed Editing --
"Open a new (empty) tab by pressing CTRL-T. Prompts for name of file to edit
map <C-T> :tabnew<CR>:edit
"Open a file in a new tab by pressing CTRL-O. Prompts for name of file to edit
map <C-O> :tabfind
"Switch between tabs by pressing Shift-Tab
map <S-Tab> gt


"-- Cursors --
" highlight Cursor guifg=white guibg=black
" highlight iCursor guifg=white guibg=black
" set guicursor=n-v-c:block-Cursor
" set guicursor+=i:ver100-iCursor
" set guicursor+=n-v-c:blinkoff0
" set guicursor+=i:blinkwait10

set wildignore+=*.pyc,*.o,*.class,*.lo,.git,vendor/*,node_modules/**

" CommandT
map <silent> <leader>ff :CommandT<CR>
map <silent> <leader>fb :CommandTBuffer<CR>
map <silent> <leader>fr :CommandTFlush<CR>

"hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white 
set cursorline


set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_quiet_messages = { "type": "style" } 
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_include_dirs = ['/spot/dev/3rdParty/cpp/SQLAPI/latest/gcc-4.7.3/include', '/opt/29West/LBM_4.2.5/Linux-glibc-2.5-x86_64/include/']
let g:syntastic_c_include_dirs = ['/spot/dev/3rdParty/cpp/SQLAPI/latest/gcc-4.7.3/include', '/opt/29West/LBM_4.2.5/Linux-glibc-2.5-x86_64/include/', '/usr/local/include/hiredis']

" Python syntastic settings
let g:syntastic_python_checkers=['flake8']
"let g:syntastic_python_flake8_args='--ignore=E501,E225'

"format JSON
map <Leader>j %!python -m json.tool<CR>

"format XML
map <Leader>x %!tidy -xml -q -i<CR>

" set nobackup       "no backup files
" set nowritebackup  "only in case you don't want a backup file while editing
" set noswapfile     "no swap files
"
"nerdtree
" open nerdtree with ctrl+n
map <C-n> :NERDTreeToggle<CR>

" vim-commentary ensure // comments instead of /*comment*/
autocmd FileType c,cpp,cs,java setlocal commentstring=//\ %s
